---
- name: Adminer Directory Exists
  file:
    path: '/opt/adminer'
    state: directory
    recurse: yes

- name: Download Adminer
  get_url:
    url: http://www.adminer.org/latest.php
    dest: '/opt/adminer/adminer.php'
    mode: 0644

- name: Copy Adminer Conf
  copy:
    src: 'adminer.conf'
    dest: /etc/apache2/conf.d/adminer.conf
    owner: root
    group: root
    mode: 0644
    force: yes
  notify:
    - apache2 | restart