---
- name: Run As Vagrant User
  lineinfile:
    dest: "/etc/apache2/envvars"
    regexp: "^export APACHE_RUN_USER="
    line: "export APACHE_RUN_USER=vagrant"
    state: present
  notify:
    - apache2 | restart

- name: Run As Vagrant Group
  lineinfile:
    dest: "/etc/apache2/envvars"
    regexp: "^export APACHE_RUN_GROUP="
    line: "export APACHE_RUN_GROUP=vagrant"
    state: present
  notify:
    - apache2 | restart

- name: Grant Vagrant Ownership
  file:
    dest: "{{ item }}"
    owner: vagrant
    group: vagrant
    recurse: yes
  with_items:
    - /var/www
    - /var/lock/apache2
