---
- name: APT Get/Install Minimal
  apt: "name={{ item }} state=present"
  with_items:
    - php5
    - libapache2-mod-php5

- name: APT Get/Install Packages
  apt: "name={{ item }} state=present"
  with_items:
    - php5-cli
    - php5-common
    - php5-curl
    - php5-dev
    - php5-fpm
    - php5-gd
    - php5-imap
    - php5-mcrypt
    - php5-mysqlnd
    - php-pear
    - php5-pgsql
    - php5-sqlite
    - php5-xmlrpc